cassandra_n1:
  image: cassandra:2.2.4
  ports:
    - "9042:9042"
    - "9160:9160"
  hostname: cassandra_n1
  environment:
    CASSANDRA_CLUSTER_NAME: "samsdb"
    CASSANDRA_ENDPOINT_SNITCH: "PropertyFileSnitch"
    CASSANDRA_DC: "DC1"
    CASSANDRA_RACK: "R1"
    CASSANDRA_START_RPC: "true"
#cassandra_n2:
#  image: cassandra:2.2.4
#  hostname: cassandra_n2
#  links:
#    - cassandra_n1
#  volumes:
#    - ./scripts:/etc/cassandra/scripts
#  environment:
#    CASSANDRA_CLUSTER_NAME: "samsdb"
#    CASSANDRA_ENDPOINT_SNITCH: "PropertyFileSnitch"
#    CASSANDRA_SEEDS: "cassandra_n1"
#    CASSANDRA_DC: "DC1"
#    CASSANDRA_RACK: "R2"